### ISSUE TITLE
create melange-app breaking  with latest release (v1.3.0)

### ISSUE THREAD

**Issue by villuminati** [dmmulroy/create-melange-app#111]
`npm`, `pnpm`, `bun` fail with v1.3.0(latest)

the command i ran:

`pnpm create melange-app@latest`

<img width="1113" alt="image" src="https://github.com/user-attachments/assets/5a66c78d-ca9a-4191-a150-35a28c427c34">

My system is Macos Apple Silicon.

I am able to run: 
`pnpm create melange-app@1.1.3`

So the issue seems to be introduced in the latest release.

**Comment by muqiuhan** [comment]
![image](https://github.com/user-attachments/assets/f7fd9698-7aee-470c-808f-bae1b78a06ca)

I had the same problem.

- node version: v22.3.0
- pnpm version: 9.10.0
- npm version: 10.8.1

**Comment by anmonteiro** [comment]
This should have been fixed by v1.3.2
