### ISSUE TITLE
Fresh project with ESBuild fails to `dune build`

### ISSUE THREAD

**Issue by smondet** [dmmulroy/create-melange-app#114]
```default
 $ eval $(opam env)
 $ dune build
File "src/App.re", line 46, characters 17-24:
46 |         ~bundler=Esbuild,
                      ^^^^^^^
Error: This variant expression is expected to have type
         Cma_configuration.Bundler.t
       There is no constructor Esbuild within type Cma_configuration.Bundler.t
```

I tried `opam pin add dune --dev` and same result.

**Comment by smondet** [comment]
Noting that this fails when OCaml is chosen as the language (i.e. `src/cma_configuration/bundler.ml` is generated in ocaml but not App.re).

When choosing ReasonML as the syntax `src/cma_configuration/bundler.re` does have the `Esbuild` case.

**Comment by Khady** [comment]
would be worth having a new release to include this fix
