### ISSUE TITLE
Failed to install OCaml toolchain on Ubuntu

### ISSUE THREAD

**Issue by emilpriver** [dmmulroy/create-melange-app#42]
Hey,
Using create-melange-app and get stuck when installing OCaml toolchain, unfortonatley am I not able to provide you more information then this image.

Is there anyway to see logs or verbose output? Maybe a verbose output would be a nice feature? :D 

![image](https://github.com/dmmulroy/create-melange-app/assets/34039674/a60253fd-9cde-4e86-b8d7-8a0365e90557)

**Comment by emilpriver** [comment]
it might be related to this error?
![image](https://github.com/dmmulroy/create-melange-app/assets/34039674/15a95200-6ee5-4f6c-bbec-5fa06e240bf4)

**Comment by leostera** [comment]
If create-melange-app is using the global `opam` we definitely want to set up the default remote to `opam.ocaml.org` so this won't happen

**Comment by emilpriver** [comment]
upgrading opam with  `opam update && opam upgrade` did solve this issue
![image](https://github.com/dmmulroy/create-melange-app/assets/34039674/d08697b6-da3f-46ad-bfd1-bd986418d045)

**Comment by dmmulroy** [comment]
We probably also want to add version constraints to our env_check process

**Comment by emilpriver** [comment]
Or letting the user know they have a old version? Some people install opam different( ex next)  and don't update version the normal way

**Comment by JoaoAlexNunes** [comment]
I think is because Debian distros don't have the newest packages, so when people install opam fewer are the ones who update and upgrade it

**Comment by dmmulroy** [comment]
#43 Should have hopefully resolved this.
