### ISSUE TITLE
Feedback: more verbouse output during steps

### ISSUE THREAD

**Issue by emilpriver** [dmmulroy/create-melange-app#52]
Would it be good with a more verbose output when running the CLI. The general thought I had when I ran CMA was that I didn't know what's happening so when I got a error during "install ocaml toolchains" didn't I know how to fix it until I ran the commands myself and did see the error.
With a more verbose output of what's going then I think more users would be able to follow what's happening under the hood.

**Comment by dmmulroy** [comment]
Great feedback, we're adding that now!

**Comment by emilpriver** [comment]
Hey, i'm closing this issue as this have been implemented. Nice job! :D
