### ISSUE TITLE
Guide to add OCaml/ReasonML package

### ISSUE THREAD

**Issue by kevanantha** [dmmulroy/create-melange-app#60]
For me as a beginner, I am a bit confused how to add some package e.i `melange-json`. Do I have to add on the *.opam file or just run `opam install melange-json` directly on the terminal but it does not update the *.opam file automatically.

**Comment by dmmulroy** [comment]
I've thought about this a bit at the beginning of the project. It definitely, at the very least, warrants documentation in the README generated by CMA, but I also wonder if we could make installing ocaml dependencies into CMA.

Something like:

`create-melange-app ocaml-install melange-json` 

and or bake it in as an `npm script` in the generated `package.json` files so users could do:

`npm run ocaml-install melange-json` 

and under the covers CMA would run:

1. Update the users `dune-project` with the new dependency
2. Run `eval $(opam env)
3. Run `dune b {project-name}.opam`
4. Run `opam update`
3. Run `opam install . --deps-only --yes`

**Comment by kevanantha** [comment]
> and or bake it in as an `npm script` in the generated `package.json` files so users could do:
> 
> `npm run ocaml-install melange-json`
> 
> and under the covers CMA would run:
> 
> 1. Update the users `dune-project` with the new dependency
> 2. Run `eval $(opam env)`
> 3. Run `dune b {project-name}.opam`
> 4. Run `opam update`
> 5. Run `opam install . --deps-only --yes`

I think I am okay with this approach

now for the quickest work-around is add section "How to add pakcage" that say step 1 - 5 on the README. wdyt?

**Comment by JoaoAlexNunes** [comment]
I think we can add either a link in readme file to a GitHub repo or some page that is like how to do stuff in ocaml/reasonml and CMA

Or add sections on how to do that things directly to the readme file

**Comment by dmmulroy** [comment]
Closed by [95967ec](https://github.com/dmmulroy/create-melange-app/commit/95967ec40fb47d3e11e821611e2cda9332c4651e)
