### ISSUE TITLE
Readme File not updating contributors

### ISSUE THREAD

**Issue by JoaoAlexNunes** [dmmulroy/create-melange-app#64]
Don't know why but readme file only shows 3 people instead of 5/6 I tried to go to the site and in the site it actually loads all

**Comment by dmmulroy** [comment]
Looks like it's likely cache'ing, it has updated on my end since the other day: 

<img width="989" alt="image" src="https://github.com/dmmulroy/create-melange-app/assets/2755722/69ce3745-9223-4902-b078-9f249d2e6baf">
