### ISSUE TITLE
Bump to melange v.3.0.0-51

### ISSUE THREAD

**Issue by dmmulroy** [dmmulroy/create-melange-app#82]
Currently blocked by https://github.com/ocaml/opam-repository/pull/25227

**Comment by kevanantha** [comment]
https://github.com/ocaml/opam-repository/pull/25227 already merged

**Comment by kevanantha** [comment]
waiting for [upgrade-melange-to-3](https://github.com/dmmulroy/create-melange-app/tree/dmmulroy/upgrade-melange-to-3) to be merged 🐐✌️

**Comment by dmmulroy** [comment]
Working on this today!

**Comment by dmmulroy** [comment]
We've bumped!
