### ISSUE TITLE
go to source 2nd level fails

### ISSUE THREAD

**Issue by ryskajakub** [dmmulroy/create-melange-app#87]
When I'm browsing the files of the project with vscode using ocaml platform plugin, when I use go to source feature, it works.

When I'm in the code of dependency of the project like React, I start to see errors in every file
![Screenshot from 2024-03-04 21-03-22](https://github.com/dmmulroy/create-melange-app/assets/993363/49ed62b6-2a70-447c-ba0b-6f2c3309a67d)

**Comment by dmmulroy** [comment]
I'm not sure this is a bug with CMA, but rather an issue for `dune` or `melange` itself. I'll take a closer look this evening though.

**Comment by ryskajakub** [comment]
I'm not sure if providing the goal of this project is making it work anywhere, be it vscode, vim ... I actually though expected this to work as a standard dev enviroment feature

**Comment by dmmulroy** [comment]
Ah I see - I'm glad you got that working. I know the dune and opam teams are working diligently this year to make some serious quality of life improvements - including merging them into one tool and improving LSP support.
