### ISSUE TITLE
Running create-melang-app fails

### ISSUE THREAD

**Issue by KaranAhlawat** [dmmulroy/create-melange-app#95]
`npm create melange-app@latest` or `pnpm create melange-app@latest` fails with `Cannot find package melange.js` (`ERR_MODULE_NOT_FOUND`)

This is on Node v20. This was working fine just a couple days ago, so not sure what changed. Maybe it's the new release?

**Comment by dmmulroy** [comment]
Confirmed, the release I put out this morning broke - remedying now.

**Comment by dmmulroy** [comment]
Should be fixed w/ `@latest`/`v1.1.3`
