### ISSUE TITLE
Including '/' in a project name causes an unclear error

### ISSUE THREAD

**Issue by yashveer-bika** [dmmulroy/create-melange-app#98]
I have Node.js v21.7.1. The issue is shown below. I have opam installed and initialized. I tried bun and pnpm as well, got the same error. 

Am I missing something?

<img width="735" alt="Screenshot 2024-04-06 at 11 10 37 PM" src="https://github.com/dmmulroy/create-melange-app/assets/38543198/4a468459-03da-4feb-90a4-a1e42e74e6c0">

<img width="718" alt="Screenshot 2024-04-06 at 11 10 51 PM" src="https://github.com/dmmulroy/create-melange-app/assets/38543198/3eb5d09f-9afd-47b8-bb81-9cd3223c8430">

**Comment by dmmulroy** [comment]
I believe the issue is that there is `/` in the project directory. I just tried doing `foo/bar` and it failed for me with the same error, however using `foobar` worked fine.

**Comment by dmmulroy** [comment]
We should improve the regex validation here to prevent `/` in the project name: https://github.com/dmmulroy/create-melange-app/blob/develop/src/core/fs.ml#L47-L74

**Comment by dmmulroy** [comment]
`[a-z_0-9.]` I think we need to escape the `.`

**Comment by JohnBakhmat** [comment]
I checked the current regex on regex101, test case of `bekka/ui` should not be possible.  
[https://regex101.com/r/F43nZc/1](https://regex101.com/r/F43nZc/1)
Looking into what can cause this bug now

**Comment by JohnBakhmat** [comment]
I figured that regex doesn't check for `/` because before project name is passed into `validate` function, a function in src/core/fs.ml trims `bekka/` and all we are left is `ui`, which is a valid name. Why it breaks after it tho 🤔

**Comment by dmmulroy** [comment]
https://github.com/dmmulroy/create-melange-app/pull/99#issuecomment-2044895275
